### ISSUE TITLE
Vanish not working properly

### ISSUE THREAD

**Issue by FlooferDoofer** [ArchitectSMP/k8s-gitops#88] opened 2021-02-23 13:35 UTC
Shadow (member, no other permissions) can see players who are in vanish mode
And login and logout messages still appear in the in-game chat + the Discord channel
Meaning vanish does not work at all at the moment

**Comment by bloodycoffin** [comment] 2021-02-23 14:06
Duplicate of ArchitectSMP/mc-config#46

**Closed by bloodycoffin** 2021-02-23 14:06 UTC
Labels: invalid
